name: Checks

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  pod-lint:
    runs-on: macos-11

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.1"
      - uses: actions/checkout@v2
      - name: Run lint
        run: pod lib lint --allow-warnings
  swift-pm:
    runs-on: macos-11

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.1"
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphoneos --show-sdk-path`" -Xswiftc "-target" -Xswiftc "arm64-apple-ios15.0"
